# Generated by Django 3.1.5 on 2021-01-25 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('amount', models.TextField(null=True)),
                ('status', models.CharField(choices=[('B', 'Bought'), ('P', 'Pending'), ('NA', 'Not Available')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groceryitems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
