# Generated by Django 3.1.5 on 2021-01-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_groceryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='status',
            field=models.TextField(choices=[('Bought', 'Bought'), ('Pending', 'Pending'), ('Not Available', 'Not Available')]),
        ),
    ]
