# Generated by Django 3.1.5 on 2021-01-25 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0005_auto_20210125_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
