# Generated by Django 3.1.5 on 2021-01-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0007_auto_20210125_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='status',
            field=models.TextField(choices=[('BOUGHT', 'BOUGHT'), ('PENDING', 'PENDING'), ('NOT AVAILABLE', 'NOT AVAILABLE')], default='PENDING', max_length=50),
        ),
    ]
